---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-kafka-consumer
  name: java-kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-kafka-consumer
  template:
    metadata:
      labels:
        app: java-kafka-consumer
    spec:
      containers:
      - name: java-kafka-consumer
        image: mrabbah/spring-boot-kafka-consumer:latest
        env:
          - name: CA_CRT
            valueFrom:
              secretKeyRef:
                name: kafka-cluster-cluster-ca-cert
                key: ca.crt
          - name: USER_CRT
            valueFrom:
              secretKeyRef:
                name: java-kafka-consumer
                key: user.crt
          - name: USER_KEY
            valueFrom:
              secretKeyRef:
                name: java-kafka-consumer
                key: user.key
          - name: BOOTSTRAP_SERVERS
            value: kafka-cluster-kafka-bootstrap:9093
          - name: TOPIC
            value: filtred-users-parallel
          - name: GROUP_ID
            value: java-kafka-consumer
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "10000"