apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: filtred-users-parallel
  labels:
      strimzi.io/cluster: kafka-cluster
spec:
  replicas: 2
  partitions: 1
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: sbstream
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: users-topic-parallel
        operation: Read
      - resource:
          type: topic
          name: users-topic-parallel
        operation: Describe
      - resource:
          type: topic
          name: filtred-users-parallel
        operation: Write
      - resource:
          type: topic
          name: ufiltred-users-parallel
        operation: Create
      - resource:
          type: topic
          name: filtred-users-parallel
        operation: Describe